### ISSUE TITLE
Context based audit settings

### ISSUE THREAD

**Issue by andyjp94** [netlify-labs/netlify-plugin-lighthouse#147]
I've just setup this plugin but I'm having issues and suspect I'm doing something wrong. I've set a lighthouse config that works perfectly well for my production branch. When used against my branches however it fails miserably with terrible performance and poor PWA scores. This makes sense because it is only the production branch that gets properly optimised by Netlify. At least that is my understanding

I would like to be able to configure audit thresholds for branches and audit thresholds for production. This is because I still care about things like accessibility on the branches but not necessarily performance due to them not being optimised in the same ways as the production branch. Is this possible right now? I tried it by using build contexts like this but it didn't work:
```
[build]
  [[plugins]]
    package = "@netlify/plugin-lighthouse"

    # optional, fails build when a category is below a threshold
    [plugins.inputs.thresholds]
      # On builds that aren't production the performance stats
      # are not accurate
      performance = 0
      accessibility = 0.7
      best-practices = 0.8
      seo = 0.85
      pwa = 1

[context.production]
  [[plugins]]
    package = "@netlify/plugin-lighthouse"

    # optional, fails build when a category is below a threshold
    [plugins.inputs.thresholds]
      performance = 0.65
      accessibility = 0.7
      best-practices = 0.8
      seo = 0.85
      pwa = 1
```

I looked at the [documentation](https://www.netlify.com/blog/2020/05/21/localize-your-environment-variables-by-context-with-build-plugins/) and it looks like it would be possible to find out what the context is from `process.env`. If an attempt was made to add this feature would it be welcome or is this not something that you'd want to support?

**Comment by erezrokah** [comment]
Hi @andyjp94 this is something we would like to support - not at a specific plugin level though. See https://github.com/netlify/build/issues/1169. I suggest we track it under that issue - can you please describe your use case there?

Closing this issue in favor that one. Please comment if more information is required

**Comment by ehmicky** [comment]
This has been implemented! :tada: 

More information in [this comment](https://github.com/netlify/build/issues/1169#issuecomment-818017760). Please let us know if this works as expected.
