### ISSUE TITLE
How to run locally? `yarn local`?

### ISSUE THREAD

**Issue by drewrwilson** [netlify-labs/netlify-plugin-lighthouse#150]
Hi! Thank you for making this plugin! 

**Describe the bug**
I don't understand how to run it locally based on the Readme. In the Readme it says to to edit the `.env` file and then run `yarn local`. What does `local` refer to? Installing the package didn't add a script named `local` to my `package.json`. Do I need to add a script to my `package.json`? If so, what should it run? 

Thank you again for the plugin!

**Comment by erezrokah** [comment]
Hi @drewrwilson, sorry for the confusion - those instructions aren't clear enough.
By running locally we mean running this repo in development mode. See that script in this repo `package.json`:
https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/ee0c321dc8fb0da252bbc0259a82aa1d623751d4/package.json#L7

When developing your own project/site I suggest you use our CLI and the `netlify build` command:
https://cli.netlify.com/commands/build/

**Comment by drewrwilson** [comment]
Got it! Thanks for explaining. I misunderstood and thought that running it locally meant generating a Lighthouse report while working I was working on my app locally. That makes sense that it means when running this repo locally. Thank you for clarifying.
