### ISSUE TITLE
Docs: Update readme to explain where to find default output

### ISSUE THREAD

**Issue by KyleBlankRollins** [netlify-labs/netlify-plugin-lighthouse#249]
**Describe the bug**
The current readme isn't clear about where users can expect to find the Lighthouse report by default. It does show how to configure an optional sub directory, but doesn't indicate that the default output is in the **Deploy details** log.

If people aren't aware that's where to look, they could miss it entirely and think it's not working.

**Additional context**
Got some docs feedback asking about where to find Lighthouse output. I won't link it here, but seems we could better guide users.

**Comment by erezrokah** [comment]
Thanks @KyleBlankRollins, that makes a lot of sense.

The current docs for this plugin is the `README` file. It would make a great contribution if you'd like to propose one.

**Comment by KyleBlankRollins** [comment]
Thanks for confirming, @erezrokah! I'll open a PR for this.
