### ISSUE TITLE
LHError: Failed with error: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by alexjfno1** [netlify-labs/netlify-plugin-lighthouse#37]
**Describe the bug**

Lighthouse is timing out when trying to audit the page.

```
4:26:25 PM: ┌──────────────────────────────────────────────────────┐
4:26:25 PM: │ 2. onSuccess command from @netlify/plugin-lighthouse │
4:26:25 PM: └──────────────────────────────────────────────────────┘
4:26:25 PM: ​
4:26:25 PM: Serving and scanning site from directory out
4:26:25 PM: Tue, 30 Jun 2020 15:26:25 GMT ChromeLauncher Waiting for browser.
4:26:25 PM: Tue, 30 Jun 2020 15:26:25 GMT ChromeLauncher Waiting for browser...
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT ChromeLauncher Waiting for browser.....
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT ChromeLauncher Waiting for browser.....✓
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT config:warn InspectorIssues gatherer requested, however no audit requires it.
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT status Connecting to browser
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT status Resetting state with about:blank
4:26:26 PM: Tue, 30 Jun 2020 15:26:26 GMT status Benchmarking machine
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Initializing…
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, MainDocumentContent, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, TraceElements, InspectorIssues, SourceMaps
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Resetting state with about:blank
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Setting up network for the pass trace
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Cleaning browser cache
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Beginning devtoolsLog and trace
4:26:27 PM: Tue, 30 Jun 2020 15:26:27 GMT status Loading page & waiting for onload
4:26:27 PM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
4:26:27 PM: [DEP0066] 
4:26:27 PM:     at new module.exports (/opt/build/repo/node_modules/union/lib/response-stream.js:50:60)
4:26:27 PM:     at new module.exports (/opt/build/repo/node_modules/union/lib/routing-stream.js:30:17)
4:26:27 PM:     at Server.requestHandler (/opt/build/repo/node_modules/union/lib/core.js:27:25)
4:26:27 PM:     at Server.emit (events.js:315:20)
4:26:27 PM:     at parserOnIncoming (_http_server.js:790:12)
4:26:27 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
4:27:12 PM: Tue, 30 Jun 2020 15:27:12 GMT Driver:warn Timed out waiting for page load. Checking if page is hung...
4:27:13 PM: Tue, 30 Jun 2020 15:27:13 GMT Driver:warn Page appears to be hung, killing JavaScript...
4:27:43 PM: Tue, 30 Jun 2020 15:27:43 GMT status Disconnecting from browser...
4:27:43 PM: Tue, 30 Jun 2020 15:27:43 GMT ChromeLauncher Killing Chrome instance 1690
4:27:43 PM: Error: PROTOCOL_TIMEOUT
4:27:43 PM: ​
4:27:43 PM: ┌────────────────────────────────────────────┐
4:27:43 PM: │ Plugin "@netlify/plugin-lighthouse" failed │
4:27:43 PM: └────────────────────────────────────────────┘
4:27:43 PM: ​
4:27:43 PM:   Error message
4:27:43 PM:   LHError: Failed with error: PROTOCOL_TIMEOUT
4:27:43 PM:   PROTOCOL_TIMEOUT
4:27:43 PM: ​
4:27:43 PM:   Plugin details
4:27:43 PM:   Package:        @netlify/plugin-lighthouse
4:27:43 PM:   Version:        1.2.1
4:27:43 PM:   Repository:     git+https://github.com/netlify-labs/netlify-plugin-lighthouse.git
4:27:43 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-lighthouse
4:27:43 PM:   Report issues:  https://github.com/netlify-labs/netlify-plugin-lighthouse/issues
4:27:43 PM: ​
4:27:43 PM:   Error location
4:27:43 PM:   In "onSuccess" event in "@netlify/plugin-lighthouse" from netlify.toml and package.json
4:27:43 PM:       at Timeout._onTimeout (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
4:27:43 PM: ​
4:27:43 PM:   Resolved config
4:27:43 PM:   build:
4:27:43 PM:     base: /opt/build/repo/app1
4:27:43 PM:     command: yarn build
4:27:43 PM:     environment:
4:27:43 PM:       - REVIEW_ID
4:27:43 PM:     ignore: git diff --quiet HEAD^ HEAD ../app1/
4:27:43 PM:     publish: /opt/build/repo/app1/out
4:27:43 PM:   plugins:
4:27:43 PM:     - inputs: {}
4:27:43 PM:       origin: config
4:27:43 PM:       package: '@netlify/plugin-lighthouse'
```

**To Reproduce**

The repository is set up in the following manor:

`package.json` <- with `@netlify/plugin-lighthouse` dev dependency
`app1/netlify.toml`
`app1/out` <- this is where the static files are outputted to.
`app1/....` <- basic Next.js files & structure

`app1/netlify.toml` contains the following:

```
[build]
  command = "yarn build"
  publish = "out"
  ignore = "git diff --quiet HEAD^ HEAD ../app1/"

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
```

**Additional context**

* Deploying from a monorepo structure where the toml file is in the sub directory where the app source is and the base directory is set.
* Using Next.js to build and export the app into static files to be served.
* Running the plugin locally using the `out` directory worked fine. The issue just occurs when running on Netlify.

**Comment by erezrokah** [comment]
Thanks @alexjfno1,

> * Running the plugin locally using the `out` directory worked fine. The issue just occurs when running on Netlify.

Do you mean by running `netlify build` from the `app1` directory?

> `....` <- basic Next.js files & structure

That is under `app1` right?

**Comment by alexjfno1** [comment]
> Do you mean by running `netlify build` from the `app1` directory?

I cloned the plugin repo, built a version of my Next.js app under `out` and then changed the `.env` to point to that `out` dir. `PUBLISH_DIR=../monorepo/app1/out`. Running `yarn local` then ran successfully.

 
> `....` <- basic Next.js files & structure
> That is under app1 right? 

Sorry I should have been clearer, yes it is all under `app1`. I'll edit the issue to make this clearer.

**Comment by erezrokah** [comment]
Cool, do you mind trying with `netlify build` for debugging purposes?
I'll try to create the same setup and reproduce.

**Comment by alexjfno1** [comment]
> Cool, do you mind trying with `netlify build` for debugging purposes?
> I'll try to create the same setup and reproduce.

I've ran this command from the `app1` directory and it worked as expected.

**Comment by alexjfno1** [comment]
I've found this issue on Lighthouse which could be related - https://github.com/GoogleChrome/lighthouse/issues/6512

**Comment by erezrokah** [comment]
Thanks, that issue is huge 😄 

Forgot to ask previously, can you share the `npm/yarn/node` versions you use locally + on Netlify?

**Comment by alexjfno1** [comment]
`12:10:32 PM: Now using node v12.18.0 (npm v6.14.4)`
`12:10:36 PM: Installing NPM modules using Yarn version 1.22.4`

We're using yarn workspaces too.

I tried with another Next.js app in the same monorepo with identical setup and it worked first time 🤔 

I also tried running the failing build and clearing the cache but that had no effect either.

The only real difference I can see is that the Netlify apps were created at different times but I can't see that being the issue.

**Comment by erezrokah** [comment]
Hi @alexjfno1,
I created this repo https://github.com/erezrokah/next-js-lighthouse in an attempt to reproduce.
Also see build log (it fails due to accessibility threshold): https://app.netlify.com/sites/zealous-newton-40af6b/deploys/5efcb04e1e80870008ac0f27

These are my build settings:
![image](https://user-images.githubusercontent.com/26760571/86264951-d684bd00-bbcb-11ea-877f-5cd29a6a1fda.png)

I also had to create an empty `yarn.lock` file under `app` to force Netlify to install `yarn`.

Can you please verify this setup is similar to yours?

**Comment by alexjfno1** [comment]
I've taken a look and it's very similar to what we have. The only thing I haven't got is the build.environment settings in the `netlify.toml` file.

**Comment by erezrokah** [comment]
> The only thing I haven't got is the build.environment settings in the `netlify.toml` file

Thanks, I did that to make sure I use the same `yarn/node` versions as your setup and don't think that should be related to the bug. I'll try removing that part.

**Comment by alexjfno1** [comment]
Here are a couple of things I have tried:

1. Using a new Netlify app but deploying the same code and config. That failed in an identical way to the original app.

2. Added Lighthouse plugin to another app in the monorepo (almost identical setup just and bit more lightweight). That was successful and had no errors.

3. Remove all content for original app so that it is a basic page. That was successful and had no errors.

So based off the findings of 3 it suggests that something in our app code is causing Chrome to crash. My next steps will be to try and find what triggers it to crash.

**Comment by erezrokah** [comment]
Thanks for digging into this! I'm sure it would be helpful for other users of the plugin to track this down

**Comment by alexjfno1** [comment]
So after some poking around I've come to the conclusion that it's a `<video>` component that is causing it to crash. It's a large hero video so is probably quite resource heavy. All I can think of is that Netlify is lacking the resources to run it and causing the Chrome instance to crash. I've seen a few issues similar to this that mention docker and the suggestions are to increasing the memory of the image. I'm not aware that you can do this with Netlify?

So I'm happy to put this down to a Lighthouse / Chrome / Netlify issue and not an issue of the plugin.

**Comment by erezrokah** [comment]
Thanks, that's very helpful. Let me check if there is an option to disable playing videos via Chrome flag first.

**Comment by erezrokah** [comment]
@alexjfno1, do you mind setting up a repo with that video so I can experiment?

**Comment by alexjfno1** [comment]
Sure @erezrokah, I'll raise a PR shortly.

**Comment by alexjfno1** [comment]
@erezrokah here is a PR: https://github.com/erezrokah/next-js-lighthouse/pull/2

I've tested on Netlify and it crashes in the same way.

**Comment by erezrokah** [comment]
Thank, I'll see what I can do on the plugin side and also contacted the relevant team at Netlify.

**Comment by alexjfno1** [comment]
Thanks for helping out @erezrokah, much appreciated!

**Comment by erezrokah** [comment]
We've seen this error before and never had a consistence reproduction, so this is huge progress for us.
Much appreciated.

**Comment by erezrokah** [comment]
@alexjfno1 my PR https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/41 fixes the crash, but looks like there is another issue with Lighthouse reporting `null` performance when there are videos on the site.
I think this should be reported as a Lighthouse bug, WDYT?

**Comment by alexjfno1** [comment]
I haven't seen the issue first hand but if it's the lighthouse library reporting null it sounds to me like it's an issue for them. 

Thanks for the fix, I'll give it a go tomorrow at some point.
