### ISSUE TITLE
How to specify path to audit?

### ISSUE THREAD

**Issue by leader22** [netlify-labs/netlify-plugin-lighthouse#44]
Hi team.

We are using role based redirects like this.

```
/* /paid/:splat 200 Role=paid
/* /free/:splat 200
```

So just adding this plugin (without `audit_url`) ends up with status code `404` beacuse nothing is served at `http://localhost:5000/index.html`.

How can we check `/free`?

> This may be another issue but, if possible we want to check multiple paths.

Solutions may be

- Adding new param to specify `http://locahost:5000/${HERE}`
  - #43 was intended PR to this
- Adding new param to specfy `http-server`'s `root` param
- etc..

Any suggestions?

**Comment by erezrokah** [comment]
Thanks so much for opening this issue @leader22. A very valid use case.
Would it make sense for the plugin to perform two audits in that case?

**Comment by leader22** [comment]
You’re welcome. 🐱 

Well, are there any workarounds or plans to implement?(or should I send some PRs?)

**Comment by erezrokah** [comment]
I just put this up https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/45
