### ISSUE TITLE
How do I see a list of audits failing during a build?

### ISSUE THREAD

**Issue by narthur** [netlify-labs/netlify-plugin-lighthouse#46]
When this plugin fails a build, I'd like a way to see a list of issues that contributed to the reduced scores. I see that the plugin logs verbosely, but it's very difficult to find the problems amid all the passed tests. I also tried running a lighthouse audit locally, but it gave a score of 100% to areas that the plugin gave a score of 89%, so I still don't know what audits failed.

Is there a way to easily see a list of audits that failed during a build?

**Comment by erezrokah** [comment]
@narthur Thanks for opening this issue.

This is a very good point.

Not sure if we should just log the related failures or post the results somewhere.
Posting the results would probably require some kind of integration with a 3rd party service.

Maybe start with a relevant summary just for the categories that are failing with specific failures and improve from there.
WDYT?

**Comment by narthur** [comment]
@erezrokah I think just logging a summary for the specific failed categories for review in the CI logs is perfect for my use case. It would be really slick if it could post the summary back to the GitHub PR when applicable, but I realize that might take quite a bit more work.
