### ISSUE TITLE
Improve error handling of invalid JSON in `audits`

### ISSUE THREAD

**Issue by ehmicky** [netlify-labs/netlify-plugin-lighthouse#79]
When the `audits` `inputs` contains invalid JSON, the error message is currently:

```
Unexpected token o in JSON at position 1 
    /opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/config.js:46:19 getConfiguration
    /opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/index.js:214:26 onPostBuild
```

Adding some `try`/`catch`/`failBuild` block around `JSON.parse()` could help build a more precise error message.

https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/ca0f50b66ad1531f100cc78202798f46de319868/src/config.js#L46

[Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5f5a155ca287f90018a8c2ab)

**Comment by erezrokah** [comment]
Adding some more context that this should only happen when someone is passing the `audits` as an env variables:
https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/ca0f50b66ad1531f100cc78202798f46de319868/src/config.js#L44

**Comment by ehmicky** [comment]
In theory, couldn't users pass a JSON string to `input.audits` (although they are not supposed to)? We don't do type checking on `inputs` yet unfortunately.

**Comment by erezrokah** [comment]
Yes, I agree, especially considering that `toml` is not a very easy format to nest objects and arrays.

I think that ideally it should be handled by Netlify build doing schema validations on inputs instead of each plugin validation them.

We can quickly fix it in the plugin for now.

**Comment by ehmicky** [comment]
For information, schema validations on inputs is being drafted at https://github.com/netlify/build/issues/1053, but we never got around to implementing it. I think most of the implementation time will actually be in building the UI for this.
