### ISSUE TITLE
Generate an HTML report and store it in a designated output path

### ISSUE THREAD

**Issue by sunlee-newyork** [netlify-labs/netlify-plugin-lighthouse#99]
**Is your feature request related to a problem? Please describe.**
No problem, just a pure feature request. I want to be able to specify an output path where an HTML report can be written. I also want to be able to separate out environment-specific instructions (i.e. development, staging, production), though I am aware of the separate feature request for environment-specific configurations [here](https://github.com/netlify/build/issues/1169).

**Describe the solution you'd like**
I want an option in `netlify.toml` where I can indicate an output path where an HTML report of the results can be written to. I also want to an option to assign different output path values for each environment.

For example:
```
[contexts.develop]
[plugins.inputs.outputs]
  path = "assets/lighthouse/develop"

[contexts.staging]
[plugins.inputs.outputs]
  path = "assets/lighthouse/staging"

[contexts.production]
[plugins.inputs.outputs]
  path = "assets/lighthouse/production"
```

**Describe alternatives you've considered**
No alternatives for now - I have not figured out a way to generate an HTML report file via Netlify. 

**Additional context**
Right now, the `lighthouse` package takes an `--output-path` argument where an HTML report will be written to, once the tests complete.

**Comment by erezrokah** [comment]
Thank you @sunlee-newyork, great feature to have.
Since you mentioned https://github.com/netlify/build/issues/1169 I think different envs is out of scope for this feature.
Where should the report be saved? Should it be deployed with the site? I can't think of any other persistent storage at the moment (that doesn't require an additional auth mechanism).
If we deploy it with the site, it can simplify different envs since each deploy will have a generated report linked to it.

**Comment by sunlee-newyork** [comment]
Yes, I was thinking deploying with the site, included in the static assets build, so that it's publicly accessible.

And yes, I agree! It would simplify differentiating environments - each environment can live in its own assets folder. Note the environment-specific paths included in the example config above. I was also thinking each report filename could be timestamped for versioning.

**Comment by paulbjensen** [comment]
Afternoon,

We have a fork of this repo to help provide this feature: https://github.com/anephenix/netlify-plugin-lighthouse

The lighthouse html report is generated and saved at this file path: <netlify_app_base_dir>/out/lighthouse.html

I will clean up the fork a bit (make it dynamic, add tests) and submit it as a PR later on.

Regards,

Paul Jensen
